### PR TITLE
Increase CPU and memory for CI because default Github runner resource doubled

### PR DESCRIPTION
**Pull request by gq1**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/variantcalling/tree/main/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by gq1** [comment]
@muffato 
It seems increasing the resources for CI for this pipeline didn't improve anything. It took around 5mins both before and after the change.

And also this CI is not just for testing on Github, I can use it on my laptop and farm. The laptop may not have 4 cores or 10G memory and also the requirement may be wasteful on the farm. 

I know some other pipelines may have CI profile just for Github, maybe we should treat this pipeline by pipeline, not just apply the changes to all of them.

**Comment by muffato** [comment]
Those are very good points. Yes, it makes sense to decide this on a pipeline-per-pipeline basis

**Comment by gq1** [comment]
Probably I will not merge this, just close it.

**Comment by gq1** [comment]
This resource config is actually from nf-core template:
https://github.com/sanger-tol/variantcalling/blob/TEMPLATE/conf/test.config

Does the nf-core update their template? The runner updating in 17 Jan and the latest nf-core release 2.13.1 on 29th Feb.

I will check it any changes from the template.

**Comment by muffato** [comment]
Yes, nf-core still update the template, although perhaps not every release. Maybe they don't know about the GitHub CI Runner change either.

**Comment by muffato** [comment]
OK to close this one

**Comment by gq1** [comment]
More resources are not necessary and this profile can be used not just in Github runnder.

**Pull request closed without merging**
