### PR TITLE
Release1.1.0 - dev

### PR DESCRIPTION
**Pull request by gq1**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/variantcalling/tree/main/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
@gq1 : is a command-line / samplesheet that was working with version 1.0 still working ? (just checking if a minor version bump is appropriate).

**Comment by gq1** [comment]
> @gq1 : is a command-line / samplesheet that was working with version 1.0 still working ? (just checking if a minor version bump is appropriate).

Still working if the bam/cram files are aligned, otherwise  `--align` flag needed. I think 1.1.0 ok.

**Review by muffato — COMMENTED** [review]
- Can you add a `CITATION.cff` like https://github.com/sanger-tol/genomenote/blob/dev/CITATION.cff ? (I'm just realising I forgot to make one for read-mapping). Follow the format of the genomenote one and take some content from https://zenodo.org/records/7890528 ("Export" section on the bottom of the right-hand-side menu and select "Citation File Format")
- The Mermaid files should be called `.mmd`, not `.md`
- The PNG has very large borders on the side. The PNG I get from mermaid.live is perfectly cropped to the content

**Review by muffato — COMMENTED** [review]
The PNG I got from mermaid.live is actually transparent ! Even better

**Review by muffato — APPROVED** [review]

**Pull request merged**
