### PR TITLE
Automate input

### PR DESCRIPTION
**Pull request by priyanka-surana**
This PR add automated input from ToL. Ignore the `assets` and `.github` changed files, they are the result of linting fixes.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/variantcalling/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/variantcalling _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
Why is there both `modules/local/samtools_view.nf` and `modules/nf-core/modules/samtools/view/` ? I think only the former is included in the subworkflow ?

**Comment by priyanka-surana** [comment]
We are using the `local` version, but eventually I want to import `fai` without explicitly including it as a parameter, but that needs some engineering that is not  included in this sprint. So the `nf-core` is for future purposes. If you want I can exclude it for now?

**Comment by muffato** [comment]
OK, no that's fine. Let's leave it for now

**Review by muffato — APPROVED** [review]
Same code as in https://github.com/sanger-tol/nf-core-pipeline/pull/2

**Comment by priyanka-surana** [comment]
The integration into a workflow is the main increment between this feature and https://github.com/sanger-tol/nf-core-pipeline/pull/2

**Pull request merged**
